name: lincs-complimentarity-go
channels:
- conda-forge
- bioconda
dependencies:
- conda-forge::jupyter
- conda-forge::jupyterlab
- conda-forge::r-irkernel
- conda-forge::nb_conda_kernels
- conda-forge::widgetsnbextension
- conda-forge::jupyter_contrib_nbextensions
- conda-forge::r-dplyr
- conda-forge::r-readr
- conda-forge::r-tidyr
- bioconda::bioconductor-topgo=2.46.0
- bioconda::bioconductor-org.hs.eg.db=3.14.0
- bioconda::bioconductor-go.db=3.14.0
